route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'cyclos-alert'
            channel: '#it-alerts'
            api_url: 'https://hooks.slack.com/services/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'